### ISSUE TITLE
Take line-spacing into account

### ISSUE THREAD

**Issue by sandinmyjoints** [tarsiiformes/which-key-posframe#2]
When line-spacing is non-nil, the height of the child frame is not great enough to show all the lines.

**Comment by sandinmyjoints** [comment]
Workaround: `(setq which-key-posframe-parameters '(line-spacing . nil))`

**Comment by tarsius** [comment]
Yes, the height calculation is purely line/character based. I do not plan to implement support for pixel-wise calculation.

Are you sure your workaround works? I believe the value of that option is supposed to be an alist, not a single cons-cell (or a string as the option's custom type claims). I am also not sure this is used at all--I don't see how it is put to use in `posframe--create-posframe`.
